import {STORAGE_KEY,emptyState,loadState,addTask,toggleTask,removeTask,addNote,removeNote,addHabit,toggleHabitToday,removeHabit,addFocus,stats,exportState,importState} from './core.js';
let state=localStorage.getItem(STORAGE_KEY)?loadState(localStorage.getItem(STORAGE_KEY)):emptyState();
const $=s=>document.querySelector(s); const esc=s=>{const d=document.createElement('div');d.textContent=s;return d.innerHTML};
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function render(){const s=stats(state);$('#stats').innerHTML=`<article><b>${s.openTasks}</b><span>Open tasks</span></article><article><b>${s.completedTasks}</b><span>Completed</span></article><article><b>${s.habitsDone}/${s.habitsTotal}</b><span>Habits today</span></article><article><b>${s.focusMinutes}</b><span>Focus minutes</span></article>`;$('#tasks').innerHTML=state.tasks.map(t=>`<li><button class="check" data-task="${t.id}">${t.done?'✓':'○'}</button><span class="${t.done?'done':''}">${esc(t.title)}</span><button class="danger" data-del-task="${t.id}">×</button></li>`).join('')||'<li class="empty">No tasks yet.</li>';$('#habits').innerHTML=state.habits.map(h=>{const done=h.dates.includes(new Date().toISOString().slice(0,10));return `<li><button class="check" data-habit="${h.id}">${done?'✓':'○'}</button><span>${esc(h.name)}</span><button class="danger" data-del-habit="${h.id}">×</button></li>`}).join('')||'<li class="empty">No habits yet.</li>';$('#notes').innerHTML=state.notes.map(n=>`<article class="note"><p>${esc(n.text)}</p><button class="danger" data-del-note="${n.id}">Delete</button></article>`).join('')||'<p class="empty">No notes yet.</p>';$('#focusTotal').textContent=`${state.focusMinutes} min`}
$('#taskForm').onsubmit=e=>{e.preventDefault();state=addTask(state,$('#taskInput').value);e.target.reset();save()};$('#habitForm').onsubmit=e=>{e.preventDefault();state=addHabit(state,$('#habitInput').value);e.target.reset();save()};$('#noteForm').onsubmit=e=>{e.preventDefault();state=addNote(state,$('#noteInput').value);e.target.reset();save()};document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.task)state=toggleTask(state,b.dataset.task);else if(b.dataset.delTask)state=removeTask(state,b.dataset.delTask);else if(b.dataset.habit)state=toggleHabitToday(state,b.dataset.habit);else if(b.dataset.delHabit)state=removeHabit(state,b.dataset.delHabit);else if(b.dataset.delNote)state=removeNote(state,b.dataset.delNote);else return;save()});
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportState(state)],{type:'application/json'}));a.download=`personal-dashboard-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};$('#import').onchange=async e=>{try{state=importState(await e.target.files[0].text());save();alert('Backup imported.')}catch(err){alert(`Import failed: ${err.message}`)}e.target.value=''};
let left=1500,tick=null,end=0;function paint(){const m=Math.floor(left/60),s=left%60;$('#timer').textContent=`${m}:${String(s).padStart(2,'0')}`}function stop(){clearInterval(tick);tick=null}$('#start').onclick=()=>{if(tick)return;end=Date.now()+left*1000;tick=setInterval(()=>{left=Math.max(0,Math.ceil((end-Date.now())/1000));paint();if(!left){stop();state=addFocus(state,25);save();alert('Focus session complete.');left=1500;paint()}},250)};$('#reset').onclick=()=>{stop();left=1500;paint()};
$('#theme').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('personal-dashboard:theme',document.documentElement.classList.contains('light')?'light':'dark')};if(localStorage.getItem('personal-dashboard:theme')==='light')document.documentElement.classList.add('light');$('#date').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date());render();paint();
